[package]
name = "tower-timeout"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
tower = { version = "0.1", path = "../" }
tokio-timer = "0.1"
