language: rust

rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    - secure: LU4wJZYCqDdxKVGFKv8XInk6GzE5ubVVu9g8vXbkyXOS2+sNhT1bMjLE+7jxFwZTSnaCXmQ5+Vo6thpnGEmndVdvbvsmYL0EswPhAXcatgc4zG+ntjbo6x1Fl+VE9l3+84yB5jWIGx1YCPBbG1hkW0QyaxPTOHnrdqcD3KEbkGYFea69mLGFLDB+0GZxr8VeNag38qXZt/yp4C8KR/la7sOlAuXGBAsNQsUK1laUWg/z71KnsprBk37hqAyH+QPks0B9BDuFKO2WYwZPNx/P+S+HuVeNmNA77JKO84NOyEcVrjm3zl0AYEA1Ovofkx2UuYKeHlKlXPncTKXoHwRnFk870nubVM/YNs1k0IlOxz11YXQW3Va3zu5BlEySn8coY8q5/x/UuAe9S/eIxeT2zJNcddaKGa9oEPaL1OJZdDt2zrIpJFC8btm/3AmzRjMx00pm04nmv1eoLgMjPTpdkD6SoHIHOzkodtAMb9qfovVyLUKKFCVMA3ZBK3bO2s7N69pQol3wlDrv8lhy0ZS1YzDyJNI3gn1+nafr2o8L4BgH+ROgYXF+JSx0AFc1ZegAokUYkwBd1Q33oEMYvw/jw66qPldoonAYhI+V6du9PIRLve+G1CT8dVjFH7220Qr07Nezz7FKikIEY4hhgT7Y6Y2R0sQNJNbeiE50eWjbaEo=
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
