[package]

name = "tower"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Carl Lerche <me@carllerche.com>"]
description = """
An extensible request / response system, used to construct high-concurrency
servers and clients.
"""

documentation = "https://docs.rs/tower"
homepage = "https://tower.rs"
repository = "https://github.com/tower-rs/tower"
readme = "README.md"

[dependencies]
futures = "0.1"
