[package]
name = "tower"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "vX.X.X" git tag.
version = "0.3.1"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower/0.3.1"
description = """
Tower is a library of modular and reusable components for building robust
clients and servers.
"""
categories = ["asynchronous", "network-programming"]
keywords = ["io", "async", "non-blocking", "futures", "service"]
edition = "2018"

[features]
default = ["log"]
log = ["tracing/log"]
balance = ["discover", "load", "ready-cache", "make"]
buffer = []
discover = []
filter = []
hedge = ["filter"]
limit = []
load = ["discover"]
load-shed = []
make = []
ready-cache = []
reconnect = ["make"]
retry = []
spawn-ready = []
timeout = []
util = []

[dependencies]
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
hdrhistogram = "6.0"
indexmap = "1.0.2"
pin-project = "0.4"
rand = { version = "0.7", features = ["small_rng"] }
slab = "0.4"
tokio = { version = "0.2", features = ["rt-core", "sync", "time"] }
tower-layer = { version = "0.3", path = "../tower-layer" }
tower-service = { version = "0.3", path = "../tower-service" }
tracing = "0.1.2"

[dev-dependencies]
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
hdrhistogram = "6.0"
quickcheck = { version = "0.6", default-features = false }
tokio = { version = "0.2", features = ["macros", "stream", "sync", "test-util" ] }
tokio-test = "0.2"
tower-test = { version = "0.3", path = "../tower-test" }
tracing-subscriber = "0.1.1"
# env_logger = { version = "0.5.3", default-features = false }
# log = "0.4.1"
